import { useState } from 'react';
import { BrainCircuit, CheckCircle2, Circle, AlertCircle, Plus } from 'lucide-react';
import toast from 'react-hot-toast';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import ProgressBar from '../components/ProgressBar';
import Badge from '../components/Badge';

const AIStudyPlan = () => {
  const [tasks, setTasks] = useState([
    { id: 1, text: 'Review Calculus III Green\'s theorem notes', subject: 'MATH 301', duration: '30m', completed: true },
    { id: 2, text: 'Take a mock quiz on Quantum Entanglement', subject: 'PHYS 410', duration: '20m', completed: false },
    { id: 3, text: 'Water Sunflower and Orchid in Study Garden', subject: 'Gamification', duration: '5m', completed: false },
    { id: 4, text: 'Read lecture PDF for Data Structures chapter 4', subject: 'CS 210', duration: '45m', completed: false },
  ]);

  const toggleTask = (id) => {
    setTasks(
      tasks.map((t) => {
        if (t.id === id) {
          const nextState = !t.completed;
          if (nextState) {
            toast.success('Milestone completed! +10 XP');
          }
          return { ...t, completed: nextState };
        }
        return t;
      })
    );
  };

  const completedCount = tasks.filter((t) => t.completed).length;
  const percentage = Math.round((completedCount / tasks.length) * 100);

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Study Plan"
        subtitle="Dynamic study calendars generated by AI to guide your milestones."
        icon={BrainCircuit}
      />

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Progress summary */}
        <div className="app-card p-5 space-y-4 h-fit">
          <h3 className="font-bold card-title text-base">Plan Overview</h3>
          <p className="text-xs card-muted leading-relaxed">
            This study plan has been tailored by your StudyPulse AI assistant based on your midterm timeline and subject standings.
          </p>

          <div className="pt-2">
            <ProgressBar value={percentage} color="purple" label="Today's Progress" />
          </div>

          <div className="grid grid-cols-2 gap-4 pt-4 border-t border-slate-200 dark:border-white/5 text-center text-xs">
            <div>
              <p className="card-muted font-semibold uppercase">Completed</p>
              <p className="text-lg font-bold card-title mt-0.5">{completedCount} / {tasks.length}</p>
            </div>
            <div>
              <p className="card-muted font-semibold uppercase">Daily XP</p>
              <p className="text-lg font-bold text-success-400 mt-0.5">+{completedCount * 10} XP</p>
            </div>
          </div>
        </div>

        {/* Task List */}
        <div className="lg:col-span-2 app-panel p-5 space-y-4">
          <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-700 pb-2">
            <span className="text-sm font-semibold section-title">TODAY'S STUDY PATH</span>
            <Badge color="purple">Active Goals</Badge>
          </div>

          <div className="space-y-3">
            {tasks.map((t) => (
              <button
                key={t.id}
                onClick={() => toggleTask(t.id)}
                className={`w-full flex items-start justify-between gap-4 p-4 rounded-xl transition text-left cursor-pointer ${
                  t.completed
                    ? 'pastel-mint-card'
                    : 'pastel-blue-card'
                }`}
              >
                <div className="flex items-start gap-3 flex-1">
                  <div className="mt-0.5 flex-shrink-0">
                    {t.completed ? (
                      <CheckCircle2 className="h-5 w-5 text-success-400" />
                    ) : (
                      <Circle className="h-5 w-5 card-muted hover:text-brand-400" />
                    )}
                  </div>
                  <div>
                    <p className={`text-xs font-semibold ${t.completed ? 'card-muted line-through' : 'card-title'}`}>
                      {t.text}
                    </p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[9px] font-bold text-brand-500 dark:text-brand-300 uppercase">{t.subject}</span>
                      <span className="text-[9px] card-muted">• {t.duration}</span>
                    </div>
                  </div>
                </div>
                <Badge color={t.completed ? 'green' : 'blue'}>
                  {t.completed ? 'Done' : 'Pending'}
                </Badge>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIStudyPlan;
