import { useState } from 'react';
import { Bell, Calendar, BookOpen, Clock, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import Badge from '../components/Badge';

const RevisionReminders = () => {
  const [reminders, setReminders] = useState([
    { id: 1, subject: 'MATH 301', topic: 'Greens Theorem formulas', date: 'Today, 2:00 PM', priority: 'High', color: 'red' },
    { id: 2, subject: 'PHYS 410', topic: 'Hilbert Space operator principles', date: 'Tomorrow, 10:00 AM', priority: 'Medium', color: 'yellow' },
    { id: 3, subject: 'CS 210', topic: 'Red-Black Tree balance cases', date: 'June 12, 11:30 AM', priority: 'Low', color: 'green' },
  ]);

  const handleStudy = (topic) => {
    toast.success(`Starting focus review for ${topic}!`);
  };

  const handleSnooze = (id) => {
    setReminders(
      reminders.map((r) =>
        r.id === id ? { ...r, date: 'Snoozed by 2 hours' } : r
      )
    );
    toast('Reminder snoozed');
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Revision Reminders"
        subtitle="Spaced repetition notification reminders generated by AI based on course targets."
        icon={Bell}
      />

      <div className="max-w-2xl mx-auto app-panel p-5 space-y-4">
        <div className="flex justify-between items-center border-b border-slate-200 dark:border-white/5 pb-2">
          <span className="text-xs font-semibold card-muted">UPCOMING REVISIONS</span>
          <Badge color="purple">{reminders.length} Active</Badge>
        </div>

        <div className="space-y-3">
          {reminders.map((r) => (
            <div
              key={r.id}
              className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 p-4 rounded-xl app-card"
            >
              <div className="flex items-start gap-3">
                <div className="mt-0.5 p-2 bg-brand-500/10 rounded-lg">
                  <BookOpen className="h-4 w-4 text-brand-400" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-brand-600 dark:text-brand-300 font-mono">{r.subject}</span>
                    <Badge color={r.color}>{r.priority}</Badge>
                  </div>
                  <h4 className="text-xs font-semibold card-title mt-1">{r.topic}</h4>
                  <p className="text-[10px] card-muted mt-0.5 flex items-center gap-1">
                    <Clock className="h-3 w-3" /> {r.date}
                  </p>
                </div>
              </div>

              <div className="flex gap-2">
                <Button size="sm" variant="secondary" onClick={() => handleSnooze(r.id)}>
                  Snooze
                </Button>
                <Button size="sm" onClick={() => handleStudy(r.topic)}>
                  Review Now
                </Button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default RevisionReminders;
