import { useState, useEffect } from 'react';
import { Bell, BookOpen, Clock, Trash2, CheckCircle, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import Badge from '../components/Badge';
import { revisionService } from '../services/revision.service';

const RevisionReminders = () => {
  const [reminders, setReminders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  // Filters
  const [filterPriority, setFilterPriority] = useState('');
  const [filterStatus, setFilterStatus] = useState('Pending');

  const fetchReminders = async () => {
    try {
      setLoading(true);
      setError(null);
      const filters = {};
      if (filterPriority) filters.priority = filterPriority;
      if (filterStatus) filters.status = filterStatus;

      const data = await revisionService.getReminders(filters);
      setReminders(data.data || []);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load reminders');
      toast.error('Failed to load reminders');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReminders();
  }, [filterPriority, filterStatus]);

  const handleGenerate = async () => {
    try {
      setGenerating(true);
      const response = await revisionService.generateReminders();
      toast.success(response.message || 'Reminders generated!');
      if (response.createdCount > 0) {
        toast.success(`Generated ${response.createdCount} new reminders`);
      } else {
        toast('No new reminders to generate based on current data.', { icon: 'ℹ️' });
      }
      fetchReminders();
    } catch (err) {
      toast.error('Failed to generate reminders');
    } finally {
      setGenerating(false);
    }
  };

  const handleComplete = async (id) => {
    try {
      await revisionService.completeReminder(id);
      toast.success('Reminder completed!');
      fetchReminders();
    } catch (err) {
      toast.error('Failed to complete reminder');
    }
  };

  const handleSnooze = async (id) => {
    try {
      await revisionService.snoozeReminder(id);
      toast.success('Reminder snoozed until tomorrow');
      fetchReminders();
    } catch (err) {
      toast.error('Failed to snooze reminder');
    }
  };

  const handleDelete = async (id) => {
    try {
      await revisionService.deleteReminder(id);
      toast.success('Reminder deleted');
      fetchReminders();
    } catch (err) {
      toast.error('Failed to delete reminder');
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'High': return 'red';
      case 'Medium': return 'yellow';
      case 'Low': return 'green';
      default: return 'blue';
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'Pending': return 'purple';
      case 'Completed': return 'green';
      case 'Snoozed': return 'yellow';
      default: return 'slate';
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'No due date';
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    }).format(new Date(dateString));
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Revision Reminders"
        subtitle="Spaced repetition notification reminders generated by AI based on your study data."
        icon={Bell}
      />

      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex gap-2">
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="form-input py-2 text-sm bg-slate-50 dark:bg-slate-950/40 border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white"
          >
            <option value="">All Statuses</option>
            <option value="Pending">Pending</option>
            <option value="Completed">Completed</option>
            <option value="Snoozed">Snoozed</option>
          </select>
          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            className="form-input py-2 text-sm bg-slate-50 dark:bg-slate-950/40 border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white"
          >
            <option value="">All Priorities</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
        </div>
        
        <Button onClick={handleGenerate} disabled={generating} className="flex items-center gap-2">
          {generating ? <RefreshCw className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
          Generate Revision Reminders
        </Button>
      </div>

      <div className="max-w-3xl mx-auto app-panel p-5 space-y-4">
        <div className="flex justify-between items-center border-b border-slate-200 dark:border-slate-700 pb-2">
          <span className="text-xs font-semibold text-slate-500 dark:text-slate-400">UPCOMING REVISIONS</span>
          <Badge color="purple">{reminders.length} Active</Badge>
        </div>

        {loading ? (
          <div className="text-center py-10 text-slate-500 dark:text-slate-400">
            <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-2 text-brand-500" />
            <p>Loading reminders...</p>
          </div>
        ) : error ? (
          <div className="text-center py-10 text-red-500">
            <p>{error}</p>
          </div>
        ) : reminders.length === 0 ? (
          <div className="text-center py-10 bg-white/70 dark:bg-slate-900/70 rounded-xl border border-slate-200 dark:border-slate-700">
            <Bell className="h-10 w-10 mx-auto text-slate-400 mb-3" />
            <p className="text-slate-700 dark:text-slate-300 font-medium">No revision reminders yet.</p>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Generate reminders from your study data to get started.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {reminders.map((r) => (
              <div
                key={r.id}
                className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 p-4 rounded-xl app-card bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700"
              >
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 p-2 bg-brand-500/10 rounded-lg">
                    <BookOpen className="h-4 w-4 text-brand-500 dark:text-brand-400" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      {r.subject && (
                        <span className="text-xs font-bold text-brand-600 dark:text-brand-300 font-mono">
                          {r.subject.code || r.subject.name}
                        </span>
                      )}
                      <Badge color={getPriorityColor(r.priority)}>{r.priority}</Badge>
                      <Badge color={getStatusColor(r.status)}>{r.status}</Badge>
                    </div>
                    <h4 className="text-sm font-semibold text-slate-900 dark:text-white">{r.title}</h4>
                    {r.description && (
                      <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">{r.description}</p>
                    )}
                    <p className="text-[11px] text-slate-500 dark:text-slate-500 mt-2 flex items-center gap-1">
                      <Clock className="h-3 w-3" /> 
                      {r.status === 'Snoozed' && r.snoozeUntil ? `Snoozed until: ${formatDate(r.snoozeUntil)}` : `Due: ${formatDate(r.dueDate)}`}
                    </p>
                  </div>
                </div>

                <div className="flex gap-2 self-end sm:self-center shrink-0">
                  {r.status === 'Pending' && (
                    <>
                      <Button size="sm" variant="secondary" onClick={() => handleSnooze(r.id)}>
                        Snooze
                      </Button>
                      <Button size="sm" variant="primary" onClick={() => handleComplete(r.id)} className="flex items-center gap-1">
                        <CheckCircle className="h-4 w-4" /> Complete
                      </Button>
                    </>
                  )}
                  <button 
                    onClick={() => handleDelete(r.id)}
                    className="p-2 text-slate-400 hover:text-red-500 transition-colors ml-1"
                    title="Delete Reminder"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default RevisionReminders;
